turbo.transfer.app.name=TurboTransfer
turbo.transfer.node.name=
turbo.transfer.server.port=8080
turbo.transfer.run.mode=single
turbo.transfer.discovery.enabled=true
turbo.transfer.discovery.port=37020
turbo.transfer.discovery.interval-seconds=5
turbo.transfer.console.host=127.0.0.1
turbo.transfer.log.server-file=server.log
turbo.transfer.log.desktop-file=desktop.log
turbo.transfer.icon.dmg-enabled=true
turbo.transfer.icon.exe-enabled=true
turbo.transfer.icon.apk-enabled=true
